### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by mariushosting** [boojack/slash#1]
### Is your feature request related to a problem?

Awesome project. Please add Dark Mode!

### Describe the solution you'd like

Dark Mode option to switch from Day to Night.

**Comment by Dom9301** [comment]
Hi!

Yeah that feature would be really appreciated!

**Comment by boojack** [comment]
@mariushosting @Dom9301 Dark mode has been supported in [v0.4.4](https://github.com/boojack/slash/releases/tag/v0.4.4)
