### ISSUE TITLE
visualization by column

### ISSUE THREAD

**Issue by freeshare** [boojack/slash#13]
### Is your feature request related to a problem?

Currently, each bookmark takes up the entire width of the screen, which makes it difficult to view all the favorites as they are presented on a long page

### Describe the solution you'd like

I'd like to have an option to set the display to 2 or 3 columns, which would make it possible to view favorites more quickly.

**Comment by boojack** [comment]
Check it out in v0.3.2

<img width="908" alt="image" src="https://github.com/boojack/slash/assets/24653555/376f5f99-aef1-4023-ade2-73619ba2f17c">

**Comment by freeshare** [comment]
Thank you for this reactivity, it's perfect!
