### ISSUE TITLE
Store bookmarks as JSON

### ISSUE THREAD

**Issue by developerbuzz** [boojack/slash#15]
### Is your feature request related to a problem?

HI, loving your bookmark app, but it would be nice if there is an option to store the bookmarks in a flat file format rather than a database.  This would make it easier to import bookmarks and would be recoverable should this project be archived.  

### Describe the solution you'd like

Ideally I'd like the bookmarks to be stored as a simple extension to one of the browser formats.  Chromium base browsers such as Edge and Chrome uses a simple JSON format for example.  I added an additional tags collection to one of my bookmark files and restarted the browser without any issues. 

Databases are fine, but they're not very portable and require backup strategies that can be troublesome.  A simple file backup would be far easier.

### Additional context

![image](https://github.com/boojack/slash/assets/23062252/9b78a697-bdc4-4d73-a156-6016984e6433)

**Comment by boojack** [comment]
> it would be nice if there is an option to store the bookmarks in a flat file format rather than a database.

We use SQLite as the database, so it will be only a `.db` file. You can execute SQL statements to export the data.
