### ISSUE TITLE
few suggestions

### ISSUE THREAD

**Issue by lordfiSh** [boojack/slash#16]
### Describe the solution you'd like

hey great tool, here a few Suggestions :-) 
- autofill out the Name Field, with the Title of the Webpage IF not filed out 
- Save [Open Graph protocol](https://ogp.me/) Data, looks like there is a Option for that, but it issued used? 
- Show Screenshot of the Site as a Option (via Open Graph)
- show the date of the last visit

**Comment by monlor** [comment]
up! 
* Support web snapshots, png and pdf
* Support sorting by conditions, creation date, access date, name, etc.

**Comment by boojack** [comment]
Please split your suggestions into separate issues, one suggestion per issue.

So that it will be easier to describe the problem and solution.
