### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by antitiron** [boojack/slash#2]
### Is your feature request related to a problem?

Thanks for a nice project, looks marvellous

### Describe the solution you'd like

If there are a lot of links, filtering may not help. I think that the ability to search by title or other fields could speed up this process.

**Comment by boojack** [comment]
Close by https://github.com/boojack/slash/commit/11205566ac88b13ffdf48fb18164834cfe2f9fcb, and will be released in next version.

**Comment by antitiron** [comment]
Beautiful work, thank you!
