### ISSUE TITLE
Buttons to change display

### ISSUE THREAD

**Issue by soundneedle** [boojack/slash#21]
### Is your feature request related to a problem?

To facilitate quick reviews of all my entries, a button to change view from detail to summary is preferred over having to click thru screens via search. Currently I have to click 3 times to change to compact/full. This should ideally be one click.

### Describe the solution you'd like

Add button(s) on the main screen to allow switching display to full/compact.

**Comment by boojack** [comment]
How about using a switch instead of the selector? This button may not be used often, so it may look awkward when placed outside. 

<img width="524" alt="image" src="https://github.com/boojack/slash/assets/24653555/42fe8cb8-9f4d-4e06-9913-4dfdfd0fce9b">
