### ISSUE TITLE
Mobile mode

### ISSUE THREAD

**Issue by Dom9301** [boojack/slash#22]
### Is your feature request related to a problem?

no, not a real problem, but a useful convenience

### Describe the solution you'd like

automatically apply a graphical style that allows Slash to be used via a smartphone browser without messing up the interface

I'm using Slash right now on my home server and it's great.

**Comment by boojack** [comment]
> messing up the interface

We have implemented a responsive layout, is there anything wrong?

<img width="416" alt="image" src="https://github.com/boojack/slash/assets/24653555/0c429ab4-aa34-4078-8b8a-680cbab2dba2">

**Comment by boojack** [comment]
> The problem remains that if a link name is very long, it comes out of the margins

It had been fixed in https://github.com/boojack/slash/commit/93ed3c81ffb1d7d9273382a74309806cd67cd437

**Comment by Dom9301** [comment]
Oh wow.

Thank you! Have a nice day!
