### ISSUE TITLE
When accessing the public URL, an error of 'Missing access token' will occur

### ISSUE THREAD

**Issue by f97** [boojack/slash#24]
### Describe the bug

An error 401 occurs instead of accessing the shortened link.

```js
{
  "error": "code=401, message=Missing access token",
  "message": "Missing access token"
}
```

### Steps to reproduce

1. Open the browser's incognito mode (not logged in).
2. Access https://demo.slash.yourselfhosted.com/s/ai-infra (a public shortcut).

### Expected behavior

Successfully accessed the shortened link.

### Screenshots or additional context

<img width="1440" alt="image" src="https://github.com/boojack/slash/assets/110044923/3ee5f9fa-bce6-497d-a63b-bb84767d4d6d">

**Comment by boojack** [comment]
Fixed in https://github.com/boojack/slash/commit/946548b33aa288a9f5a3b853a39f6c0ff173a8b4. Thanks for your reporting!
