### ISSUE TITLE
Issue on firefox

### ISSUE THREAD

**Issue by Arkheon** [boojack/slash#3]
### Describe the bug

Cant create an account or log on firefox /and chrome

Have  to use Edge to create an account and log into it .

I use docker to host Slash

`
method=GET uri=/api/v1/user/me status=401 error=code=401, message=Missing access token
`

### Steps to reproduce

N/A

### Expected behavior

N/A

**Comment by boojack** [comment]
Fixed in https://github.com/boojack/slash/commit/86078b097d23c9a69d93b9fe645e8b892c21b08d

**Comment by Arkheon** [comment]
Ty , could you please update your docker image ? :D

tyvm
