### ISSUE TITLE
Settings Page does not have Access Token Section

### ISSUE THREAD

**Issue by sasnak** [boojack/slash#33]
### Describe the bug

I tried with both regular and admin account, extension doesn't have the ability to create an access token.

### Steps to reproduce

Click on name upper right hand corner
Choose Settings
Edit and Change Password are only options - Access Token does not exist.
I'm using the Unraid install using "stevenlgtm/slash:latest" repository.

### Expected behavior

Should be able to click on create - access token.

**Comment by boojack** [comment]
You need to deploy an instance of slash first. :）

https://github.com/boojack/slash/blob/main/docs/install-browser-extension.md

**Comment by sasnak** [comment]
I have the server installed that's how I created both admin and user
accounts.

**Comment by boojack** [comment]
@sasnak The latest version should be `v0.4.3`. Please make sure that you have a correct version.
