### ISSUE TITLE
disable the registration of new users

### ISSUE THREAD

**Issue by clikalogo** [boojack/slash#34]
### Describe the bug

**It is not possible to disable the registration of new users.**

Performed git:
git clone https://github.com/boojack/slash.git

Created local docker image:
docker build -t yourselfhosted/slash:local_v0.4.3 .

After installing version v0.4.3 in docker (local image), it is not possible to view the option in settings to disable new user registration.

**Any variable (Docker ENV) or database modification (Sqlite) to disable new users?**

### Steps to reproduce

settings

### Expected behavior

**Any variable (Docker ENV) or database modification (Sqlite) to disable new users?**

### Screenshots or additional context

![image](https://github.com/boojack/slash/assets/107278009/14fcee31-6856-4f2c-b3df-2b748ac8cbd4)

**Comment by boojack** [comment]
Scroll down your page?

<img width="1087" alt="image" src="https://github.com/boojack/slash/assets/24653555/a84955ed-764e-4201-a3c4-4517ca56a903">

---

BTW, please do not use the unreleased version. You can find the stable latest version in https://hub.docker.com/r/yourselfhosted/slash

**Comment by clikalogo** [comment]
It's already at the end. There is nothing else available below.

![image](https://github.com/boojack/slash/assets/107278009/f058e0f4-37bf-40fd-92a8-b5e35757498b)


I've run the build a few times and the option doesn't appear. When I use the Hub Docker image, the option to not accept new registrations appears, but I need to do my local build to change the texts (language - pt).

**Comment by boojack** [comment]
> I need to do my local build to change the texts (language - pt).

We'll support i18n in the next version, maybe it's better to make a PR for pt. So you can keep stay with the official docker image.
