### ISSUE TITLE
Suggest tags when typing

### ISSUE THREAD

**Issue by saitauthao** [boojack/slash#35]
### Is your feature request related to a problem?

Feature

### Describe the solution you'd like

Suggest tags when typing in tags to auto complete.

**Comment by boojack** [comment]
I'd like to list a tag suggestions after the input element. So you can quickly add one after clicking it.

<img width="446" alt="image" src="https://github.com/boojack/slash/assets/24653555/de32b1b4-2130-4c05-9ca8-3caad59f38cf">
