### ISSUE TITLE
Additional fields Name is Darked in Dark Mode

### ISSUE THREAD

**Issue by mariushosting** [boojack/slash#37]
### Describe the bug

if I add an additional field name and I use a dark mode theme the field name is dark (black) almost impossible to read if you use the dark mode theme.

### Steps to reproduce

if I add an additional field name and I use a dark mode theme the field name is dark (black) almost impossible to read if you use the dark mode theme.

### Expected behavior

should be another color for title if you use dark mode.

### Screenshots or additional context

![dark](https://github.com/boojack/slash/assets/37554361/311ec274-44af-4b7b-bd3a-7f80b41a2125)

**Comment by boojack** [comment]
Fixed with https://github.com/boojack/slash/commit/cb9786ef7c3a09f832a38a84e099c260721770f7
