### ISSUE TITLE
Question : Folder management

### ISSUE THREAD

**Issue by Arkheon** [boojack/slash#4]
### Is your feature request related to a problem?

i dont have the possibility to arrange my URL in folders .

Is it planned to have folders ? or do we have to use the tags ?

ty 

### Describe the solution you'd like

As a user i wish to arrange my urls by folders

**Comment by boojack** [comment]
The tag can get the same effect. I'm thinking of designing how to display all the tags first, let me know if you have any thoughts on this.

**Comment by Arkheon** [comment]
I guess some king of tag cloudwith the most used tag in big police ? 

[https://www.lifewire.com/thmb/AqMH6pmurHO2Iz0GV4jeQFQp3uU=/2121x1414/filters:fill(auto,1)/GettyImages-1087261168-5c89325946e0fb0001cbf5e2.jpg](like this ?)

**Comment by boojack** [comment]
All tags will be flattened on top for quick filtering.

![CleanShot 2023-07-27 at 23 12 11@2x](https://github.com/boojack/slash/assets/24653555/d8e5e258-a4d7-4b2a-8c80-071866dff666)
