### ISSUE TITLE
Chrome extension not working

### ISSUE THREAD

**Issue by Alsan** [boojack/slash#41]
### Describe the bug

- unable to save shortcut to my private hosted instance. i can create the shortcut directly in the site page.
- unable to open the popup dialog after the first save of shortcut
- unable to open the option page

### Steps to reproduce

1. install and setup the extension
2. create save a new shortcut
3. click on the pinned extension icon, just a little box without any content opened
4. select 'options'  from the context menu of the extension, a blank page opened, press f12, and reopen the options page again to see console log

### Expected behavior

save the shortcut as expected

### Screenshots or additional context

![2023-10-26_08:22:48](https://github.com/boojack/slash/assets/217947/806364d2-23c4-4f93-977c-44754e121ff9)

**Comment by boojack** [comment]
What's the extension version and slash instance's version you are using? I cannot reproduce in the latest one.

**Comment by Alsan** [comment]
Sorry, I don't use slash anymore, so I can't give the exact server and extension version. The extension is downloaded from chrome store, I assume that would be the most updated version, and the server is running as docker container, might be this [one](https://github.com/boojack/slash)? I can't remember, I just found this from my browser history.
