### ISSUE TITLE
Share public shortcuts to the internet

### ISSUE THREAD

**Issue by JerryWesler** [boojack/slash#42]
### Is your feature request related to a problem?

收藏的这些网页希望能支持自定义链接，展示内容就是所有public属性的书签，这样可以作为书签页，很适合导航，用途更多。

### Describe the solution you'd like

无需登录即可查看

**Comment by boojack** [comment]
Released our **Collection** in `v0.5.0`, see more in https://github.com/boojack/slash/releases/tag/v0.5.0
