### ISSUE TITLE
API Shortlink creation

### ISSUE THREAD

**Issue by fidst** [boojack/slash#6]
### Is your feature request related to a problem?

Right now, the only way to create a shortlink is via the interface.

### Describe the solution you'd like

An API to allow for easy shortlink creation.

**Comment by bryceprutsos** [comment]
+1 for this enhancement

**Comment by boojack** [comment]
API docs: https://github.com/boojack/slash/blob/main/proto/gen/api/v2/README.md#shortcutservice
How to use: https://github.com/boojack/slash/blob/main/extension/src/components/CreateShortcutsButton.tsx#L98
