### ISSUE TITLE
Create shortcuts with browser extension

### ISSUE THREAD

**Issue by boyshu** [boojack/slash#8]
### Is your feature request related to a problem?

Public links can be aggregated without logging in at the front end.
And it's great to add browser plug-ins.
I hope I can add the above related functions.

### Describe the solution you'd like

If you can achieve the above functions, I will be happy to use, and can reward you!

### Additional context

![20230723162634](https://github.com/boojack/slash/assets/47899589/546d4ebf-2ca8-409b-8f05-9103fb64fcf4)

**Comment by boojack** [comment]
Browser extension is also in the development roadmap, stay tuned!

**Comment by xiNeRoar** [comment]
I really wish to have the browser extension!

**Comment by boojack** [comment]
For Chromium based browsers(Chrome, Edge, Arc, ...), you can install the extension from the [Chrome Web Store](https://chrome.google.com/webstore/detail/slash/ebaiehmkammnacjadffpicipfckgeobg).
